name: hello-world

#trigger
on:
  push:
    branches: ["main"]

env:
  TEXT: "Juan Corea Badilla"
  

jobs: 
#pipelines
  print:
    runs-on: ubuntu-latest # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

    steps:
     - name: print-to-screen
       run: echo "Hello World ${{ env.TEXT}}"
     - name: pint-secret
       run: echo "secret value: ${{ secrets.SECRET_NAME }}"
